version: '3.8'
networks:
  local-network:
    driver: bridge

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - mongo
      - rabbitmq
      - nft
      - auction
      - projection-service
    networks:
      - local-network
  mongo:
    container_name: mongo
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    networks:
      - local-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.2-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672' # AMQP protocol port
      - '15672:15672' # HTTP management UI
    networks:
      - local-network
  nft:
    container_name: nft
    build:
      context: ./backend
      dockerfile: ./nft/Dockerfile
    environment:
      GRADLE_OPTS: "-Dorg.gradle.vfs.watch=false"
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - '8081:8081'
    networks:
      - local-network
  auction:
    container_name: auction
    build:
      context: backend
      dockerfile: auction/Dockerfile
    environment:
      GRADLE_OPTS: "-Dorg.gradle.vfs.watch=false"
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - '8080:8080'
    networks:
      - local-network
  projection-service:
    container_name: projection-service
    build:
      context: backend
      dockerfile: projectionservice/Dockerfile
    environment:
      GRADLE_OPTS: "-Dorg.gradle.vfs.watch=false"
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - '8082:8082'
    networks:
      - local-network
  nginx:
    image: nginx:latest
    ports:
      - "8083:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - local-network

