version: '3.8'
networks:
  local-network:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    networks:
      - local-network
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    depends_on:
      - mongo
      - rabbitmq
      - backend
    networks:
      - local-network
  mongo:
    container_name: mongo
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - local-network
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.2-management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - '15672:15672' # HTTP management UI
    networks:
      - local-network

  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/admin
      SPRING_DATA_MONGODB_DATABASE: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      GRADLE_OPTS: "-Dorg.gradle.vfs.watch=false" # Assuming your Dockerfile is named Dockerfile and located at the specified context
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - local-network
    restart: on-failure
