version: '3.8'
networks:
  local-network:
    driver: bridge

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      dockerfile: ../frontend/Dockerfile
      context: ../frontend
    ports:
      - 5173:5173
    depends_on:
      - mongo
      - rabbitmq
      - backend
    networks:
      - local-network
  mongo:
    container_name: mongo
    image: mongo:6.0.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    networks:
      - local-network
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11.2-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672' # AMQP protocol port
      - '15672:15672' # HTTP management UI
    networks:
      - local-network

  backend:
    container_name: backend
    build:
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongo:27017/admin
      SPRING_DATA_MONGODB_DATABASE: admin
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: password
      GRADLE_OPTS: "-Dorg.gradle.vfs.watch=false" # Assuming your Dockerfile is named Dockerfile and located at the specified context
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - '8080:8080'
    networks:
      - local-network
